# Step 1: Specify the base image
FROM node:latest

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Step 4: Copy the rest of the application code
COPY . .

EXPOSE 5173

# Step 5: Build the application
RUN npm run build

# Step 6: Start the application
CMD ["npm", "start"]
