version: '3.8'

services:
  authservice:
    build:
      context: ./authservice
      dockerfile: dockerfile
    ports:
      - "8081:8081"

  codeexecuteservice:
    build:
      context: ./codeexecuteservice
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8083:8083"
    privileged: true  # Run the container in privileged mode


  friendservice:
    build:
      context: ./friendservice
      dockerfile: dockerfile
    ports:
      - "8082:8082"

  gameservice:
    build:
      context: ./gameservice
      dockerfile: dockerfile
    ports:
      - "8085:8085" # for HTTP server
      - "8086:8086" # for WebSocket server
    
  problemservice:
    build:
      context: ./problemservice
      dockerfile: dockerfile
    ports:
      - "8084:8084"
